CONNECT:
  LICENSE: "CommonTicket"
  SITE_KEY: "S7RFSMR3-H86SC1AT-C1C18O1F-OAS3FSER-SCI3TROE"
  SERVER_NAME: "CommonTicket"
  SITE_LINK: "https://unixsystem.com.ar/CommonTicket"
  CATEGORY_DEFAULT: 1 # !IMPORTANT FOR THE COMMAND: /ticket add
  JOIN-SEND-MESSAGE: true
  MYSQL:
    HOST: localhost
    PORT: '3306'
    USER: root
    PASSWD: PASSWORD
    DATABASE: CommonTicket

COMMAND:
  TICKET:
    REGISTER: true # true / false
    MESSAGE:
      COMMAND-DISABLED: "&7[&9&lCommonTicket&7] &b➤ &cCommand disabled"
      REGISTER:
        - "&7&m-----------------------------------------------"
        - "&7[&9&lCommonTicket&7] &b➤ &fYou have registered in the site."
        - "&7[&9&lCommonTicket&7] &b➤ &fClick here > <site_link>" # CONFIGURE: CONNECT.SITE_LINK
        - "&7&m-----------------------------------------------"
      REGISTERED:
        - "&7[&9&lCommonTicket&7] &b➤ &fYou are already registered on the site"
      CREATED:
        - "&7&m-----------------------------------------------"
        - "&7[&9&lCommonTicket&7] &b➤ &fYou have created a ticket!"
        - "&a<site_link>/ticket"
        - "&7&m-----------------------------------------------"
      ACCOUNT:
        - "  &7  &7  &7  &7  &7  &7  [&9&lCommonTicket&7]"
        - "&7&m-----------------------------------------------"
        - "&b&l My account Information: &9&l↴"
        - "&b  ➤ &9User ID: &7<userid>"
        - "&b  ➤ &9Username: &7<username>"
        - "&b  ➤ &9Password: &7<password>"
        - "&b  ➤ &9UUID: &7<uuid>"
        - "&b  ➤ &9Site: &7<site_link>/profile?id=<userid>"
        - "&7&m-----------------------------------------------"
      ADD-RANK:
        - "  &7  &7  &7  &7  &7  &7  [&9&lCommonTicket&7]"
        - "&7&m-----------------------------------------------"
        - "&b&l Give rank: &9&l↴"
        - "&b  ➤ &9User ID: &7<userid>"
        - "&b  ➤ &9IGN: &7<ign>"
        - "&b  ➤ &9Rank: &7<rank>"
        - "&b  ➤ &9UUID: &7<uuid>"
        - "&b  ➤ &9Site: &7<site_link>/profile?id=<userid>"
        - "&7&m-----------------------------------------------"
MESSAGE:
  TICKET:
    LOG: "&7[&9&lCommonTicket&7] &b➤ &fYou have <ticket_totals> Ticket's"

